### ISSUE TITLE
Awesome workflow - but problems with dark themes!

### ISSUE THREAD

**Issue by haakonstorm** [bikenik/alfred-icons#1]
<img width="555" alt="Screenshot of Brave Browser Beta (25-08-2019, 13-03-31)" src="https://user-images.githubusercontent.com/193781/63649037-c6dd5200-c738-11e9-9611-8e888f7cb63a.png">

# Possible to add a feature to invert the colors for the preview? 

I am not a JS coder, but I searched a bit to at least try and provide some possible solutions:

## svg.js lightweight library, perhaps fill() ?
I am not a JS coder, but I searched a bit to at least try and find some pointers, and I found this library: maybe fill() can do it? [SVG.js](https://svgjs.com/docs/2.7/manipulating/#syntactic-sugar) 

## svg.filter.js plugin with invert() function ?
Or perhaps "invert" filter from [svg.filter.js](https://github.com/svgdotjs/svg.filter.js#invert) plugin can do it?
```
image.filterWith(function(add) {
  add.componentTransfer({
    type: 'table'
    tableValues: [1, 0]
  })
})
```

## perhaps, after downloading, just add a white background before having Alfred "quicklook" the icon? 

# Feature request :-)

## Feature to download the SVG directly, adding the copyright text in the file metadata?

**Comment by ghost** [comment]
Where did you define your key and secret to get the workflow to function?
